spring:
  application:
    name: user
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

