spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        ## 设置form表单可按put、delete方式提交
        enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
logging:
  config: classpath:logback.xml

