server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: zuul
zuul:
  routes:
    service-user:
      path: /user/**
      serviceId: user

logging:
  config: classpath:logback.xml